baseURL = 'https://people.cs.uchicago.edu/~macmillan/'
languageCode = 'en-us'
title = 'Kyle MacMillan'
theme = 'xmin'
canonifyURLs = false

[params]
  description = "A blog with beautiful sidenotes"
  footer = ""

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "Personal"
    url = "/personal/"
    weight = 2
  [[menu.main]]
    name = "Scholar"
    url = "https://scholar.google.com/citations?user=-mt8ztEAAAAJ&hl=en"
    weight = 3
